// HISTORY ITEMS
export const ADD_HISTORY_ITEM = "HISTORY/ADD_HISTORY_ITEM";
export const REMOVE_HISTORY_ITEM = "HISTORY/REMOVE_HISTORY_ITEM";
export const COPY_QUERY_HISTORY_ITEM = "HISTORY/COPY_QUERY_HISTORY_ITEM";
export const IS_SHOW_HISTORY_MENU = "HISTORY/IS_SHOW_HISTORY_MENU";
export const TOGGLE_COPY_TEXT = "HISTORY/TOGGLE_COPY_TEXT";
export const TOGGLE_HISTORY_MENU = "HISTORY/TOGGLE_HISTORY_MENU";

// HISTORY MENU
export const MENU_HISTORY_RUN = "HISTORY/MENU_RUN";
export const UPDATE_HISTORY = "HISTORY/UPDATE_HISTORY";

// AUTH
export const AUTH_LOGOUT = "AUTH/AUTH_LOGOUT";
export const AUTH_ISAUTHING = "AUTH/AUTH_ISAUTHING";
export const AUTH_SUCCESS = "AUTH/SUCCESS";
export const AUTH_FAILURE = "AUTH/FAILURE";

// CONSOLE
export const POST_REQUEST = "CONSOLE/POST_REQUEST";
export const IS_REQUESTING = "CONSOLE/IS_REQUESTING";
export const REQUEST_SUCCESS = "CONSOLE/REQUEST_SUCCESS";
export const REQUEST_FAILURE = "CONSOLE/REQUEST_FAILURE";

// FULL SCREEN
export const IS_FULL_SCREEN = "HEADER/IS_FULL_SCREEN";
export const FULL_SCREEN_TOGGLE = "HEADER/TOGGLE_FULLSCREEN";
