export const ALL_ITEMS = "HISTORY/ALL_ITEMS";
export const ADD_HISTORY_ITEM = "HISTORY/ADD_HISTORY_ITEM";
export const COPY_QUERY_HISTORY_ITEM = "HISTORY/COPY_QUERY_HISTORY_ITEM";
export const IS_SHOW_HISTORY_MENU = "HISTORY/IS_SHOW_HISTORY_MENU";
export const TOGGLE_COPY_TEXT = "HISTORY/TOGGLE_COPY_TEXT";
export const TOGGLE_HISTORY_MENU = "HISTORY/TOGGLE_HISTORY_MENU";
export const IS_FULL_SCREEN = "HEADER/IS_FULL_SCREEN";
export const FULL_SCREEN_TOGGLE = "HEADER/TOGGLE_FULLSCREEN";

// ACTION HISTORY MENU

export const MENU_HISTORY_RUN = "HISTORY/MENU_RUN";

// AUTH

export const AUTH = "AUTH";
export const AUTH_ERROR = "AUTH/ERROR";
